// Testi redatti per gli indicatori dai giri; valori e riferimenti uguali nelle sei lingue.
module.exports = {
 it: {
  assente: 'Nessuna partecipazione F1 su questo circuito in questa stagione.',
  nuovoCircuito: 'Nessuna edizione F1 su questo tracciato in questa stagione; non si trasferiscono i dati di un altro circuito.',
  passo: 'Delta mediano {delta}% rispetto ai giri confrontabili degli altri piloti: {n} giri, indice relativo {indice}/100. Un delta negativo indica tempi inferiori al riferimento. {dettaglio}',
  pochi: 'Sessione acquisita: {n} giri confrontabili; campione sotto la soglia per un indice di passo. {dettaglio}',
  stint: '{codice}: {mescola}, giri {inizio}–{fine}, {giri} giri di stint, età iniziale {eta}.',
  gomme: 'Sequenza osservata: {stint} Deriva cronometrica relativa {pendenza}% per giro su {n} stint confrontabili; indice descrittivo {indice}/100. Non isola usura, carburante o gestione volontaria.',
  gommePochi: 'Sequenza osservata: {stint} Stint filtrati insufficienti per una pendenza robusta; lunghezza e mescola sono dati osservati, non un voto di gestione.',
  recente: 'Proiezione per questo GP dai {gp} GP precedenti: {dati} Evidenza della stagione corrente; non sono tempi già misurati nel weekend futuro.',
  limite: 'Filtri: mescola asciutta, età comparabile, pit, traffico, pioggia e neutralizzazioni. Risultato condizionato al campione; vettura e condizioni non isolate.',
  stagione: '2026 fino al round {round}: gara {gara}/100 su {nr} esiti regolari; qualifica {qualifica}/100 su {nq} sessioni; ultimi 3 GP {recente}/100, variazione dell’indice {delta} sui 3 precedenti.',
  conclusione: 'Previsione aggiornata: {posizione}/{totale}, indice {indice}/100. Evidenze specifiche: passo {passo}/100, deriva gomme {gomme}/100. Sono indici descrittivi; pesi e limiti sono nel metodo pubblicato.',
  aggiornamenti: 'Profilo tecnico {squadra}: {aree}. Contesto per {circuito}; queste aree descrivono la vettura e non confermano un nuovo componente per il GP. Nessun guadagno cronometrico attribuito senza confronto verificabile.',
  strategia: '{nomina}. Storico acquisito: {sessioni} gare, {sc} interventi SC e {vsc} VSC. Stint asciutti osservati: {stint}. La finestra di sosta dipende da traffico e condizioni del weekend.',
  nomina: 'Mescole 2026 confermate: {mescole}', nonNomina: 'Riferimento storico delle mescole; la nomina 2026 non è ancora confermata dalle fonti acquisite',
  rischi: 'Storico {sessioni} gare: SC {sc}, VSC {vsc}, bandiere rosse {red}, pioggia registrata in {wet}. Campione descrittivo, non probabilità futura.',
  forza: 'Evidenze favorevoli: {campi}.', debolezza: 'Aspetti da migliorare o verificare: {campi}.',
  storicoLimite: 'Storico di vetture e regolamenti precedenti; confronto utile per il contesto del circuito, non trasferibile automaticamente al 2026.',
 },
 en: {
  assente:'No F1 participation at this circuit in this season.',nuovoCircuito:'No F1 edition at this venue in this season; data from a different circuit are not transferred.',
  passo:'Median delta {delta}% against comparable laps by other drivers: {n} laps, relative index {indice}/100. A negative delta means shorter times than the reference. {dettaglio}',
  pochi:'Session acquired: {n} comparable laps; sample below the threshold for a pace index. {dettaglio}',
  stint:'{codice}: {mescola}, laps {inizio}–{fine}, {giri} stint laps, initial tyre age {eta}.',
  gomme:'Observed sequence: {stint} Relative timing drift {pendenza}% per lap across {n} comparable stints; descriptive index {indice}/100. Does not isolate wear, fuel or deliberate management.',
  gommePochi:'Observed sequence: {stint} Too few filtered stints for a robust slope; length and compound are observed data, not a management rating.',
  recente:'Projection for this GP from the {gp} preceding GPs: {dati} Current-season evidence; these are not times already measured in a future weekend.',
  limite:'Filters: dry compound, comparable age, pit laps, traffic, rainfall and neutralisations. Conditional on the selected sample; car and conditions not isolated.',
  stagione:'2026 through round {round}: race {gara}/100 from {nr} regular outcomes; qualifying {qualifica}/100 from {nq} sessions; last 3 GPs {recente}/100, index change {delta} against the preceding 3.',
  conclusione:'Updated forecast: {posizione}/{totale}, index {indice}/100. Specific evidence: pace {passo}/100, tyre timing drift {gomme}/100. Descriptive indices; weights and limits in the published method.',
  aggiornamenti:'Technical profile {squadra}: {aree}. Context for {circuito}; these areas describe the car and do not confirm a new component for the GP. No lap-time gain attributed without a verifiable comparison.',
  strategia:'{nomina}. Acquired history: {sessioni} races, {sc} SC and {vsc} VSC interventions. Observed dry stints: {stint}. Pit timing depends on traffic and weekend conditions.',
  nomina:'Confirmed 2026 compounds: {mescole}',nonNomina:'Historical compound reference; the 2026 nomination is not yet confirmed by acquired sources',
  rischi:'History of {sessioni} races: SC {sc}, VSC {vsc}, red flags {red}, rainfall recorded in {wet}. Descriptive sample, not a future probability.',
  forza:'Favourable evidence: {campi}.',debolezza:'Areas to improve or verify: {campi}.',storicoLimite:'History with earlier cars and regulations; useful circuit context, not automatically transferable to 2026.',
 },
 fr: {
  assente:'Aucune participation F1 sur ce circuit cette saison.',nuovoCircuito:'Aucune édition F1 sur ce tracé cette saison; les données d’un autre circuit ne sont pas transférées.',
  passo:'Écart médian {delta}% aux tours comparables des autres pilotes : {n} tours, indice relatif {indice}/100. Un écart négatif indique des temps inférieurs à la référence. {dettaglio}',
  pochi:'Session acquise : {n} tours comparables; échantillon sous le seuil pour un indice de rythme. {dettaglio}',
  stint:'{codice} : {mescola}, tours {inizio}–{fine}, {giri} tours de relais, âge initial {eta}.',
  gomme:'Séquence observée : {stint} Dérive chronométrique relative {pendenza}% par tour sur {n} relais comparables; indice descriptif {indice}/100. Usure, carburant et gestion volontaire non isolés.',
  gommePochi:'Séquence observée : {stint} Trop peu de relais filtrés pour une pente robuste; longueur et gomme observées, pas une note de gestion.',
  recente:'Projection pour ce GP à partir des {gp} GP précédents : {dati} Données de la saison actuelle; pas des temps déjà mesurés lors d’un week-end futur.',
  limite:'Filtres : gomme sèche, âge comparable, arrêts, trafic, pluie et neutralisations. Résultat conditionnel à l’échantillon; voiture et conditions non isolées.',
  stagione:'2026 jusqu’au tour de championnat {round} : course {gara}/100 sur {nr} résultats réguliers; qualifications {qualifica}/100 sur {nq} sessions; derniers 3 GP {recente}/100, variation de l’indice {delta} sur les 3 précédents.',
  conclusione:'Prévision actualisée : {posizione}/{totale}, indice {indice}/100. Données spécifiques : rythme {passo}/100, dérive pneus {gomme}/100. Indices descriptifs; poids et limites dans la méthode publiée.',
  aggiornamenti:'Profil technique {squadra} : {aree}. Contexte pour {circuito}; ces domaines décrivent la voiture et ne confirment pas une nouvelle pièce pour le GP. Aucun gain chronométrique attribué sans comparaison vérifiable.',
  strategia:'{nomina}. Historique acquis : {sessioni} courses, {sc} interventions SC et {vsc} VSC. Relais secs observés : {stint}. Arrêts selon le trafic et les conditions du week-end.',
  nomina:'Gommes 2026 confirmées : {mescole}',nonNomina:'Référence historique des gommes; nomination 2026 pas encore confirmée par les sources acquises',
  rischi:'Historique de {sessioni} courses : SC {sc}, VSC {vsc}, drapeaux rouges {red}, pluie enregistrée dans {wet}. Échantillon descriptif, pas une probabilité future.',
  forza:'Données favorables : {campi}.',debolezza:'Points à améliorer ou vérifier : {campi}.',storicoLimite:'Historique de voitures et règlements antérieurs; contexte du circuit, sans transfert automatique en 2026.',
 },
 pt: {
  assente:'Nenhuma participação F1 neste circuito nesta temporada.',nuovoCircuito:'Nenhuma edição F1 neste traçado nesta temporada; dados de outro circuito não são transferidos.',
  passo:'Diferença mediana {delta}% face a voltas comparáveis dos outros pilotos: {n} voltas, índice relativo {indice}/100. Valor negativo indica tempos inferiores à referência. {dettaglio}',
  pochi:'Sessão adquirida: {n} voltas comparáveis; amostra abaixo do limiar para um índice de ritmo. {dettaglio}',
  stint:'{codice}: {mescola}, voltas {inizio}–{fine}, {giri} voltas de stint, idade inicial {eta}.',
  gomme:'Sequência observada: {stint} Deriva cronométrica relativa {pendenza}% por volta em {n} stints comparáveis; índice descritivo {indice}/100. Desgaste, combustível e gestão voluntária não isolados.',
  gommePochi:'Sequência observada: {stint} Poucos stints filtrados para uma inclinação robusta; duração e composto observados, não uma nota de gestão.',
  recente:'Projeção para este GP a partir dos {gp} GP anteriores: {dati} Evidência da temporada atual; não são tempos já medidos num fim de semana futuro.',
  limite:'Filtros: composto seco, idade comparável, boxes, tráfego, chuva e neutralizações. Resultado condicionado à amostra; carro e condições não isolados.',
  stagione:'2026 até à ronda {round}: corrida {gara}/100 em {nr} resultados regulares; qualificação {qualifica}/100 em {nq} sessões; últimos 3 GP {recente}/100, variação do índice {delta} face aos 3 anteriores.',
  conclusione:'Previsão atualizada: {posizione}/{totale}, índice {indice}/100. Evidência específica: ritmo {passo}/100, deriva pneus {gomme}/100. Índices descritivos; pesos e limites no método publicado.',
  aggiornamenti:'Perfil técnico {squadra}: {aree}. Contexto para {circuito}; estas áreas descrevem o carro e não confirmam um novo componente para o GP. Nenhum ganho cronométrico atribuído sem comparação verificável.',
  strategia:'{nomina}. Histórico adquirido: {sessioni} corridas, {sc} intervenções SC e {vsc} VSC. Stints secos observados: {stint}. Paragens dependem do tráfego e das condições do fim de semana.',
  nomina:'Compostos 2026 confirmados: {mescole}',nonNomina:'Referência histórica dos compostos; nomeação 2026 ainda não confirmada pelas fontes adquiridas',
  rischi:'Histórico de {sessioni} corridas: SC {sc}, VSC {vsc}, bandeiras vermelhas {red}, chuva registada em {wet}. Amostra descritiva, não probabilidade futura.',
  forza:'Evidências favoráveis: {campi}.',debolezza:'Aspetos a melhorar ou verificar: {campi}.',storicoLimite:'Histórico de carros e regulamentos anteriores; contexto do circuito, sem transferência automática para 2026.',
 },
 es: {
  assente:'Ninguna participación F1 en este circuito esta temporada.',nuovoCircuito:'Ninguna edición F1 en este trazado esta temporada; no se transfieren datos de otro circuito.',
  passo:'Diferencia mediana {delta}% frente a vueltas comparables de otros pilotos: {n} vueltas, índice relativo {indice}/100. Un valor negativo indica tiempos inferiores a la referencia. {dettaglio}',
  pochi:'Sesión adquirida: {n} vueltas comparables; muestra inferior al umbral para un índice de ritmo. {dettaglio}',
  stint:'{codice}: {mescola}, vueltas {inizio}–{fine}, {giri} vueltas de tanda, edad inicial {eta}.',
  gomme:'Secuencia observada: {stint} Deriva cronométrica relativa {pendenza}% por vuelta en {n} tandas comparables; índice descriptivo {indice}/100. Desgaste, combustible y gestión voluntaria no aislados.',
  gommePochi:'Secuencia observada: {stint} Pocas tandas filtradas para una pendiente robusta; duración y compuesto observados, no una nota de gestión.',
  recente:'Proyección para este GP a partir de los {gp} GP anteriores: {dati} Evidencia de la temporada actual; no son tiempos ya medidos en un fin de semana futuro.',
  limite:'Filtros: compuesto seco, edad comparable, boxes, tráfico, lluvia y neutralizaciones. Resultado condicionado a la muestra; coche y condiciones no aislados.',
  stagione:'2026 hasta la ronda {round}: carrera {gara}/100 en {nr} resultados regulares; clasificación {qualifica}/100 en {nq} sesiones; últimos 3 GP {recente}/100, variación del índice {delta} sobre los 3 anteriores.',
  conclusione:'Predicción actualizada: {posizione}/{totale}, índice {indice}/100. Evidencia específica: ritmo {passo}/100, deriva neumáticos {gomme}/100. Índices descriptivos; pesos y límites en el método publicado.',
  aggiornamenti:'Perfil técnico {squadra}: {aree}. Contexto para {circuito}; estas áreas describen el coche y no confirman un nuevo componente para el GP. Sin ganancia cronométrica atribuida sin comparación verificable.',
  strategia:'{nomina}. Histórico adquirido: {sessioni} carreras, {sc} intervenciones SC y {vsc} VSC. Tandas secas observadas: {stint}. Paradas según tráfico y condiciones del fin de semana.',
  nomina:'Compuestos 2026 confirmados: {mescole}',nonNomina:'Referencia histórica de compuestos; la selección 2026 aún no está confirmada por las fuentes adquiridas',
  rischi:'Histórico de {sessioni} carreras: SC {sc}, VSC {vsc}, banderas rojas {red}, lluvia registrada en {wet}. Muestra descriptiva, no probabilidad futura.',
  forza:'Evidencias favorables: {campi}.',debolezza:'Aspectos que mejorar o verificar: {campi}.',storicoLimite:'Histórico de coches y reglamentos anteriores; contexto del circuito, sin transferencia automática a 2026.',
 },
 de: {
  assente:'Keine F1-Teilnahme auf dieser Strecke in dieser Saison.',nuovoCircuito:'Kein F1-Rennen auf diesem Kurs in dieser Saison; Daten anderer Strecken werden nicht übertragen.',
  passo:'Median der Abweichung {delta}% zu vergleichbaren Runden anderer Fahrer: {n} Runden, relativer Index {indice}/100. Negativ bedeutet kürzere Zeiten als die Referenz. {dettaglio}',
  pochi:'Session erfasst: {n} vergleichbare Runden; Stichprobe unter der Schwelle für einen Tempoindex. {dettaglio}',
  stint:'{codice}: {mescola}, Runden {inizio}–{fine}, {giri} Stint-Runden, anfängliches Reifenalter {eta}.',
  gomme:'Beobachtete Abfolge: {stint} Relative Zeitentwicklung {pendenza}% pro Runde in {n} vergleichbaren Stints; deskriptiver Index {indice}/100. Verschleiß, Kraftstoff und bewusstes Management nicht isoliert.',
  gommePochi:'Beobachtete Abfolge: {stint} Zu wenige gefilterte Stints für eine robuste Steigung; Länge und Mischung beobachtet, keine Managementnote.',
  recente:'Prognose für diesen GP aus den {gp} vorherigen GP: {dati} Daten der aktuellen Saison; keine bereits im künftigen Wochenende gemessenen Zeiten.',
  limite:'Filter: Trockenmischung, vergleichbares Alter, Boxenrunden, Verkehr, Regen und Neutralisationen. Bedingt durch die Stichprobe; Auto und Bedingungen nicht isoliert.',
  stagione:'2026 bis Runde {round}: Rennen {gara}/100 aus {nr} regulären Ergebnissen; Qualifying {qualifica}/100 aus {nq} Sessions; letzte 3 GP {recente}/100, Indexveränderung {delta} gegenüber den 3 vorherigen.',
  conclusione:'Aktualisierte Prognose: {posizione}/{totale}, Index {indice}/100. Konkrete Daten: Tempo {passo}/100, Reifen-Zeitentwicklung {gomme}/100. Deskriptive Indizes; Gewichte und Grenzen in der veröffentlichten Methode.',
  aggiornamenti:'Technisches Profil {squadra}: {aree}. Kontext für {circuito}; diese Bereiche beschreiben das Auto und bestätigen kein neues Teil für den GP. Kein Zeitgewinn ohne überprüfbaren Vergleich zugeschrieben.',
  strategia:'{nomina}. Erfasste Historie: {sessioni} Rennen, {sc} SC- und {vsc} VSC-Einsätze. Beobachtete Trockenstints: {stint}. Boxenzeitpunkt hängt von Verkehr und Wochenendbedingungen ab.',
  nomina:'Bestätigte Mischungen 2026: {mescole}',nonNomina:'Historische Mischungsreferenz; Auswahl 2026 durch erfasste Quellen noch nicht bestätigt',
  rischi:'Historie von {sessioni} Rennen: SC {sc}, VSC {vsc}, rote Flaggen {red}, Regen erfasst in {wet}. Deskriptive Stichprobe, keine künftige Wahrscheinlichkeit.',
  forza:'Günstige Befunde: {campi}.',debolezza:'Zu verbessernde oder zu prüfende Bereiche: {campi}.',storicoLimite:'Historie früherer Autos und Regeln; Streckenkontext ohne automatische Übertragung auf 2026.',
 },
};

for (const [lang, values] of Object.entries({
 it: ['Registro FIA verificato per {squadra}: {registro}. Per {circuito} questo è il contesto documentato disponibile; non conferma componenti nuovi nel GP futuro né l’installazione sulla singola vettura. Beneficio cronometrico non isolato.', 'nessun aggiornamento dichiarato'],
 en: ['Verified FIA record for {squadra}: {registro}. For {circuito}, this is the available documented context; it does not confirm new components for a future GP or installation on an individual car. Lap-time benefit not isolated.', 'no updates declared'],
 fr: ['Registre FIA vérifié pour {squadra} : {registro}. Pour {circuito}, voici le contexte documenté disponible; il ne confirme pas de nouvelles pièces au GP futur ni leur montage sur chaque voiture. Gain chronométrique non isolé.', 'aucune évolution déclarée'],
 pt: ['Registo FIA verificado de {squadra}: {registro}. Para {circuito}, este é o contexto documentado disponível; não confirma peças novas num GP futuro nem a instalação em cada carro. Ganho cronométrico não isolado.', 'nenhuma atualização declarada'],
 es: ['Registro FIA verificado de {squadra}: {registro}. Para {circuito}, este es el contexto documentado disponible; no confirma piezas nuevas en un GP futuro ni su instalación en cada coche. Ganancia cronométrica no aislada.', 'ninguna actualización declarada'],
 de: ['Geprüfter FIA-Nachweis für {squadra}: {registro}. Für {circuito} ist dies der dokumentierte Kontext; keine Bestätigung neuer Teile beim künftigen GP oder des Einbaus in jedes Auto. Zeitgewinn nicht isoliert.', 'keine Updates gemeldet'],
})) { module.exports[lang].registroAggiornamenti = values[0]; module.exports[lang].nessunAggiornamento = values[1]; }
