// Testi controllati nelle sei lingue; i dati interpolati restano identici.
const testi = {
  it: {
    ignoto: "Non determinabile", griglia: "griglia", giri: "giri", causa: "causa F1DB",
    assente: "Nessuna partecipazione F1 documentata su questo circuito nell'edizione.",
    nota: "Classificazione e qualifica sono distinte dalla griglia. Ritiri e squalifiche non dimostrano scarso passo o degrado; l'assenza di una causa non esclude altri episodi.",
    passo: "Passo gara non misurato: mancano giri comparabili per mescola, età gomme, traffico e neutralizzazioni. Il risultato finale non misura la velocità sul giro.",
    gomme: "Gestione gomme non misurata: mancano stint e tempi comparabili. Posizioni recuperate, soste e risultato finale non isolano il degrado.",
    aggiornamenti: "Beneficio degli aggiornamenti non misurato. Componenti dichiarati o installati non dimostrano un guadagno isolato; specifica per questa vettura e questo GP da verificare.",
    stagione: "Risultati 2026 fino al limite temporale indicato; rendimento e qualifica sono indici dai risultati, non passo o capacità tecniche.",
    conclusione: "Indice descrittivo sperimentale dai risultati: {indice}/100; posizione {posizione}/{totale} nel modello semantico. È una stima, non una probabilità. Passo, gomme e beneficio aggiornamenti non misurati.",
    retro: "Ricalcolo retrospettivo con i dati sportivi anteriori a questo GP, non previsione conservata prima della gara.",
    affidabilita: "Esiti regolari, su partenze documentate: {completate}/{partenze} ({percentuale}%). Include incidenti e squalifiche; non è una misura di affidabilità meccanica.",
    confidenza: "Non calibrata: accuratezza verificata nel confronto storico, senza garanzia per questo GP.",
    strategia: "Mescole {mescole}. Strategia e degrado da verificare nelle condizioni del weekend; numero di soste non determinato.",
    compoundUnknown: "non ancora confermate nella verifica",
    outsider: "Possibili variazioni rispetto all'indice: meteo, penalità, strategia, incidenti e aggiornamenti non misurati.",
    rischio: "Rischi da verificare nel weekend: meteo, neutralizzazioni, penalità, prescrizioni gomme e affidabilità. Nessuna frequenza specifica è certificata.",
    favorevoli: "Ordine descrittivo del modello semantico, non probabilità di vittoria: ",
    difficolta: "Ultime posizioni dell'indice descrittivo, non esiti certi: ",
  },
  en: {
    ignoto: "Not determinable", griglia: "grid", giri: "laps", causa: "F1DB reason",
    assente: "No documented F1 participation at this circuit in this edition.",
    nota: "Classification and qualifying differ from the starting grid. Retirements and disqualifications do not prove poor pace or degradation; no recorded cause does not rule out other incidents.",
    passo: "Race pace not measured: comparable laps by compound, tyre age, traffic and neutralisations are missing. The final result does not measure lap speed.",
    gomme: "Tyre management not measured: comparable stints and times are missing. Positions gained, stops and the final result do not isolate degradation.",
    aggiornamenti: "Upgrade benefit not measured. Declared or fitted components do not prove an isolated gain; specification for this car and GP requires verification.",
    stagione: "2026 results up to the stated time cutoff; performance and qualifying are result indices, not pace or technical capabilities.",
    conclusione: "Experimental descriptive result index: {indice}/100; position {posizione}/{totale} in the semantic model. An estimate, not a probability. Pace, tyres and upgrade benefit not measured.",
    retro: "Retrospective calculation using sporting data preceding this GP, not a forecast saved before the race.",
    affidabilita: "Regular outcomes: {completate}/{partenze} starts ({percentuale}%). Includes incidents and disqualifications; not a measure of mechanical reliability.",
    confidenza: "Uncalibrated: accuracy assessed in the historical comparison, with no guarantee for this GP.",
    strategia: "Compounds {mescole}. Strategy and degradation require verification in weekend conditions; number of stops undetermined.",
    compoundUnknown: "not yet confirmed in this review",
    outsider: "Possible departures from the index: weather, penalties, strategy, incidents and unmeasured upgrades.",
    rischio: "Weekend risks to verify: weather, neutralisations, penalties, tyre requirements and reliability. No specific frequency is certified.",
    favorevoli: "Descriptive order of the semantic model, not win probabilities: ",
    difficolta: "Lowest descriptive indices, not certain outcomes: ",
  },
  fr: {
    ignoto: "Non déterminable", griglia: "grille", giri: "tours", causa: "cause F1DB",
    assente: "Aucune participation F1 documentée sur ce circuit pour cette édition.",
    nota: "Classement et qualifications diffèrent de la grille de départ. Abandons et disqualifications ne prouvent pas un mauvais rythme ou une dégradation; aucune cause enregistrée n'exclut d'autres incidents.",
    passo: "Rythme de course non mesuré : il manque des tours comparables par gomme, âge des pneus, trafic et neutralisations. Le résultat final ne mesure pas la vitesse au tour.",
    gomme: "Gestion des pneus non mesurée : relais et temps comparables manquants. Positions gagnées, arrêts et résultat final n'isolent pas la dégradation.",
    aggiornamenti: "Bénéfice des évolutions non mesuré. Pièces déclarées ou installées ne prouvent pas un gain isolé; spécification pour cette voiture et ce GP à vérifier.",
    stagione: "Résultats 2026 jusqu'à la limite temporelle indiquée; rendement et qualifications sont des indices de résultats, pas de rythme ou de capacités techniques.",
    conclusione: "Indice descriptif expérimental des résultats : {indice}/100; position {posizione}/{totale} dans le modèle sémantique. Estimation, pas probabilité. Rythme, pneus et bénéfice des évolutions non mesurés.",
    retro: "Calcul rétrospectif avec les données sportives antérieures à ce GP, pas une prévision sauvegardée avant la course.",
    affidabilita: "Résultats réguliers : {completate}/{partenze} départs ({percentuale}%). Inclut incidents et disqualifications; ne mesure pas la fiabilité mécanique.",
    confidenza: "Non calibrée : précision évaluée par comparaison historique, sans garantie pour ce GP.",
    strategia: "Gommes {mescole}. Stratégie et dégradation à vérifier dans les conditions du week-end; nombre d'arrêts indéterminé.",
    compoundUnknown: "pas encore confirmées dans cette vérification",
    outsider: "Écarts possibles par rapport à l'indice : météo, pénalités, stratégie, incidents et évolutions non mesurées.",
    rischio: "Risques du week-end à vérifier : météo, neutralisations, pénalités, prescriptions pneus et fiabilité. Aucune fréquence spécifique certifiée.",
    favorevoli: "Ordre descriptif du modèle sémantique, pas probabilités de victoire : ",
    difficolta: "Indices descriptifs les plus faibles, pas résultats certains : ",
  },
  pt: {
    ignoto: "Não determinável", griglia: "grelha", giri: "voltas", causa: "causa F1DB",
    assente: "Nenhuma participação F1 documentada neste circuito nesta edição.",
    nota: "Classificação e qualificação diferem da grelha de partida. Abandonos e desclassificações não demonstram mau ritmo ou degradação; a falta de uma causa registada não exclui outros incidentes.",
    passo: "Ritmo de corrida não medido: faltam voltas comparáveis por composto, idade dos pneus, tráfego e neutralizações. O resultado final não mede a velocidade por volta.",
    gomme: "Gestão de pneus não medida: faltam stints e tempos comparáveis. Posições ganhas, paragens e resultado final não isolam a degradação.",
    aggiornamenti: "Benefício das atualizações não medido. Componentes declarados ou instalados não demonstram um ganho isolado; especificação para este carro e GP a verificar.",
    stagione: "Resultados de 2026 até ao limite temporal indicado; rendimento e qualificação são índices de resultados, não de ritmo ou capacidades técnicas.",
    conclusione: "Índice descritivo experimental dos resultados: {indice}/100; posição {posizione}/{totale} no modelo semântico. Estimativa, não probabilidade. Ritmo, pneus e benefício das atualizações não medidos.",
    retro: "Cálculo retrospetivo com dados desportivos anteriores a este GP, não uma previsão guardada antes da corrida.",
    affidabilita: "Resultados regulares: {completate}/{partenze} partidas ({percentuale}%). Inclui incidentes e desclassificações; não mede a fiabilidade mecânica.",
    confidenza: "Não calibrada: precisão avaliada na comparação histórica, sem garantia para este GP.",
    strategia: "Compostos {mescole}. Estratégia e degradação a verificar nas condições do fim de semana; número de paragens indeterminado.",
    compoundUnknown: "ainda não confirmados nesta verificação",
    outsider: "Possíveis desvios do índice: meteorologia, penalizações, estratégia, incidentes e atualizações não medidas.",
    rischio: "Riscos a verificar no fim de semana: meteorologia, neutralizações, penalizações, prescrições de pneus e fiabilidade. Nenhuma frequência específica certificada.",
    favorevoli: "Ordem descritiva do modelo semântico, não probabilidades de vitória: ",
    difficolta: "Índices descritivos mais baixos, não resultados certos: ",
  },
  es: {
    ignoto: "No determinable", griglia: "parrilla", giri: "vueltas", causa: "causa F1DB",
    assente: "Ninguna participación F1 documentada en este circuito en esta edición.",
    nota: "Clasificación y calificación difieren de la parrilla de salida. Abandonos y descalificaciones no demuestran mal ritmo o degradación; la ausencia de una causa registrada no excluye otros incidentes.",
    passo: "Ritmo de carrera no medido: faltan vueltas comparables por compuesto, edad de neumáticos, tráfico y neutralizaciones. El resultado final no mide la velocidad por vuelta.",
    gomme: "Gestión de neumáticos no medida: faltan tandas y tiempos comparables. Posiciones ganadas, paradas y resultado final no aíslan la degradación.",
    aggiornamenti: "Beneficio de las actualizaciones no medido. Componentes declarados o instalados no demuestran una ganancia aislada; especificación para este coche y GP por verificar.",
    stagione: "Resultados de 2026 hasta el límite temporal indicado; rendimiento y calificación son índices de resultados, no de ritmo o capacidades técnicas.",
    conclusione: "Índice descriptivo experimental de resultados: {indice}/100; posición {posizione}/{totale} en el modelo semántico. Estimación, no probabilidad. Ritmo, neumáticos y beneficio de actualizaciones no medidos.",
    retro: "Cálculo retrospectivo con datos deportivos anteriores a este GP, no una predicción guardada antes de la carrera.",
    affidabilita: "Resultados regulares: {completate}/{partenze} salidas ({percentuale}%). Incluye incidentes y descalificaciones; no mide la fiabilidad mecánica.",
    confidenza: "No calibrada: precisión evaluada en la comparación histórica, sin garantía para este GP.",
    strategia: "Compuestos {mescole}. Estrategia y degradación por verificar en las condiciones del fin de semana; número de paradas indeterminado.",
    compoundUnknown: "todavía no confirmados en esta verificación",
    outsider: "Posibles desviaciones del índice: tiempo, penalizaciones, estrategia, incidentes y actualizaciones no medidas.",
    rischio: "Riesgos del fin de semana por verificar: tiempo, neutralizaciones, penalizaciones, prescripciones de neumáticos y fiabilidad. Ninguna frecuencia específica certificada.",
    favorevoli: "Orden descriptivo del modelo semántico, no probabilidades de victoria: ",
    difficolta: "Índices descriptivos más bajos, no resultados ciertos: ",
  },
  de: {
    ignoto: "Nicht bestimmbar", griglia: "Startplatz", giri: "Runden", causa: "F1DB-Ursache",
    assente: "Keine dokumentierte F1-Teilnahme auf dieser Strecke bei dieser Ausgabe.",
    nota: "Klassifikation und Qualifying unterscheiden sich von der Startaufstellung. Ausfälle und Disqualifikationen beweisen kein schlechtes Tempo oder hohen Abbau; keine erfasste Ursache schließt andere Zwischenfälle nicht aus.",
    passo: "Renntempo nicht gemessen: vergleichbare Runden nach Mischung, Reifenalter, Verkehr und Neutralisationen fehlen. Das Endergebnis misst keine Rundengeschwindigkeit.",
    gomme: "Reifenmanagement nicht gemessen: vergleichbare Stints und Zeiten fehlen. Gewonnene Positionen, Stopps und Endergebnis isolieren den Reifenabbau nicht.",
    aggiornamenti: "Nutzen der Updates nicht gemessen. Gemeldete oder eingebaute Teile beweisen keinen isolierten Gewinn; Spezifikation für dieses Auto und diesen GP zu prüfen.",
    stagione: "Ergebnisse 2026 bis zur angegebenen zeitlichen Grenze; Leistung und Qualifying sind Ergebnisindizes, kein Tempo oder technische Fähigkeiten.",
    conclusione: "Experimenteller deskriptiver Ergebnisindex: {indice}/100; Position {posizione}/{totale} im semantischen Modell. Schätzung, keine Wahrscheinlichkeit. Tempo, Reifen und Update-Nutzen nicht gemessen.",
    retro: "Rückblickende Berechnung mit Sportdaten vor diesem GP, keine vor dem Rennen gespeicherte Prognose.",
    affidabilita: "Reguläre Ergebnisse: {completate}/{partenze} Starts ({percentuale}%). Umfasst Zwischenfälle und Disqualifikationen; misst keine mechanische Zuverlässigkeit.",
    confidenza: "Nicht kalibriert: Genauigkeit im historischen Vergleich bewertet, ohne Garantie für diesen GP.",
    strategia: "Mischungen {mescole}. Strategie und Abbau unter den Wochenendbedingungen zu prüfen; Anzahl der Stopps unbestimmt.",
    compoundUnknown: "in dieser Prüfung noch nicht bestätigt",
    outsider: "Mögliche Abweichungen vom Index: Wetter, Strafen, Strategie, Zwischenfälle und nicht gemessene Updates.",
    rischio: "Am Wochenende zu prüfende Risiken: Wetter, Neutralisationen, Strafen, Reifenvorgaben und Zuverlässigkeit. Keine bestimmte Häufigkeit bestätigt.",
    favorevoli: "Deskriptive Reihenfolge des semantischen Modells, keine Siegchancen: ",
    difficolta: "Niedrigste deskriptive Indizes, keine sicheren Ergebnisse: ",
  },
};
function formatta(testo, valori) {
  return testo.replace(/\{(\w+)\}/g, (_, k) => String(valori[k] ?? "—"));
}
module.exports = { testi, formatta };
